// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeP6CeBOrrGfD_YKwjlPvciL7Up8Ax7bE',
    appId: '1:172414151785:web:6d96d113572fc4455186f8',
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    authDomain: 'gymbro-f4ff7.firebaseapp.com',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    measurementId: 'G-L3WEBRXNGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjE67ACESX7jel0xW-kT9Lik6BgYoGWg',
    appId: '1:172414151785:android:4f5b3671facf3d8b5186f8',
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSsjjo_3gDNTt0pGoXGFeLlAuWSJZhRUE',
    appId: '1:172414151785:ios:f2cfac3fb22e301c5186f8',
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    iosBundleId: 'com.gymbro.gymbroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSsjjo_3gDNTt0pGoXGFeLlAuWSJZhRUE',
    appId: '1:172414151785:ios:f2cfac3fb22e301c5186f8',
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    iosBundleId: 'com.gymbro.gymbroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeP6CeBOrrGfD_YKwjlPvciL7Up8Ax7bE',
    appId: '1:172414151785:web:5e782e0afd5fa57c5186f8',
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    authDomain: 'gymbro-f4ff7.firebaseapp.com',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    measurementId: 'G-J5YD9HWVMB',
  );
}
