// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


//env
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FIRE_BASE_API_KEY_WEB,
    appId: FIRE_BASE_APP_ID_WEB,
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    authDomain: 'gymbro-f4ff7.firebaseapp.com',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    measurementId: 'G-L3WEBRXNGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FIRE_BASE_API_KEY_ANDROID,
    appId: FIRE_BASE_APP_ID_ANDROID,
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FIRE_BASE_API_KEY_IOS,
    appId: FIRE_BASE_APP_ID_IOS,
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    iosBundleId: 'com.gymbro.gymbroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FIRE_BASE_API_KEY_MACOS,
    appId: FIRE_BASE_APP_ID_MACOS,
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    iosBundleId: 'com.gymbro.gymbroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: FIRE_BASE_API_KEY_WINDOWS,
    appId: FIRE_BASE_APP_ID_WINDOWS,
    messagingSenderId: '172414151785',
    projectId: 'gymbro-f4ff7',
    authDomain: 'gymbro-f4ff7.firebaseapp.com',
    storageBucket: 'gymbro-f4ff7.firebasestorage.app',
    measurementId: 'G-J5YD9HWVMB',
  );
}
